"""
Django settings for books project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
from typing import Optional

import environ
from aiogram import Dispatcher

env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h7qugcuil47d3-t&=i#t)ekxx4lk)!zqe-056-0q_sf52f)mza'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "*"
]

# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'books_catalog'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'books.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'books.wsgi.application'

DATA_DIR = env('DATA_DIR')

BOOKS_DIR = env('BOOKS_DIR')

"""
Путь до директории с изображениями с обложками
"""
COVERS_DIR = DATA_DIR + "/covers/"
"""
Token of TG bot
"""
TG_TOKEN = env('TG_TOKEN')

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR + '/db.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__)) + "/../"

"""
Максимальное количество воркеров для разбора архивов
"""
MAX_WORKERS_ARCHIVE = 1
"""
Максимальная очередь с названиями архивов для парсинга архивов, собственно
"""
MAX_QUEUE_ARCHIVE = 200
"""
Имя логгера
"""
LOGGER_NAME = "fb2_parser"
"""
Максимальное количество воркеров-парсеров fb2-файлов
"""
MAX_WORKERS_FB2 = 3
"""
Максимальная длина очереди с fb2-файлами для последующего парсинга
"""
MAX_QUEUE_FB2 = 500
"""
Очередь результатов парсинга
"""
MAX_QUEUE_RES = 1000
"""
Адрес эластика
"""
ES_HOST = env('ES_HOST')
"""
Размер батча для отправки в эластик
"""
ES_BATCH_SIZE = 1000
"""
Количество строк на странице выдачи
"""
TG_COUNT_PER_PAGE = 5
"""
Размер выборки при поиске в эластике
"""
TG_ES_MAX_SIZE = 1000
"""
Сохраняем и отправляем ли обложки книг
"""
COVERS_ENABLED = True

"""
Название параметра с конфигом эластика
"""
CONFIG_NAME_ES_INDEX = "es_index"
"""
Папка, с загруженными вручную файлами
"""
MANUAL_UPLOAD_DIR = "uploads"
